version: '3'

services:
  app:
    ports:
      - "9000:8000"
    restart: unless-stopped
    depends_on:
      - redis
      - db
    links:
      - redis
      - db
  
  redis:
    image: "redis:alpine"
    restart: unless-stopped

  db:
    image: "postgres:alpine"
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testdb
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
 